#ifndef __SendPMDialog__
#define __SendPMDialog__

/**
@file
Subclass of SendPMDialogBase, which is generated by wxFormBuilder.
*/

#include "SendPMDialogBase.h"

/** Implementing SendPMDialogBase */
class SendPMDialog : public SendPMDialogBase
{
protected:
	// Handlers for SendPMDialogBase events.
	void OnCloseDialog( wxCloseEvent& event );
	void OnInitDialog( wxInitDialogEvent& event );
	void OnTextComboNick( wxCommandEvent& event );
	void OnSendClick( wxCommandEvent& event );
	
public:
	/** Constructor */
	SendPMDialog( wxWindow* parent );
};

#endif // __SendPMDialog__
